from pymongo import MongoClient, UpdateOne
import ast

uri1 = ""

mongo_conn1 = MongoClient(uri1, connect=False)
source_coll_1 = mongo_conn1['company']['sic_codes_v1']
source_coll_2 = mongo_conn1['company']['sic_codes_v2']
source_coll_3 = mongo_conn1['company']['sic_codes_v3']
source_coll_4 = mongo_conn1['company']['sic_codes_v4']
target_coll = mongo_conn1['company']['sic_codes_final']
target_failed = mongo_conn1['company']['sic_codes_failed']

sector_map = {'Banking': ['Banks', 'Credit Unions', 'Lending', 'Payments', 'Non-Bank Holding Company'],
              'Capital Markets': ['Investment Bank', 'Security & Commodity Exchanges'],
              'Insurance': ['Insurance Carriers', 'Distribution', 'Health Plans & Health Insurance'],
              'Wealth & Asset Management': ['REITs and Other Trusts', 'Wealth Management', 'Asset Management',
                                            'Private Equity & Venture Capital'],
              'Fin-Tech / Software': ['Technology that performs financial services',
                                      'Software Supporting Financial Services Companies'],
              'Hardware Manufacturing': ['Computers & Office Equipment', 'Consumer Electronics',
                                         'Measurement Equipment', 'Communications Equipment'],
              'Semiconductor & Components': ['Electrical Components', 'Semi conductor Manufacturing'],
              'Software & Services': ['Software & Programming Services', 'Technology Business Services',
                                      'Software supporting Financial Services',
                                      'Technology that performs financial services',
                                      'Software / Technology Supporting Providers and Hospitals',
                                      'Fitness / Health Apps', 'MedTech / Health Tech'],
              'Automobile Services': ['Automobile Parking', 'Miscellaneous Automotive Services',
                                      'Utility Trailer & Recreational Vehicle Rental'],
              'Business Services': ['Consumer Credit Reporting / Mercantile Services',
                                    'Detective, Guard, & Armored Car Services',
                                    'Mailing, Reproduction & Commercial Art Services', 'Security Systems Services',
                                    'Staffing Agencies', 'Miscellaneous Business Services'],
              'Electrical Repair Shops': ['Repair Shops & Related Services'],
              'Engineering, Accounting, Research, Mgmt Services': ['Accounting Services', 'Consulting Services',
                                                                   'Management Services', 'Public Relations',
                                                                   'Research Services', 'Health Consulting'],
              'Legal Services': ['Legal Services'],
              'Personal Services': ['Funeral Homes & Funeral Services', 'Miscellaneous Personal Services',
                                    'Tax Return Preparation Services'],
              'Miscellaneous Services': ['Miscellaneous Services'], 'Health Plans': ['Health Plans & Health Insurance'],
              'Medical Devices and Diagnostics': ['Device Manufacturers', 'Diagnostics & Laboratories'],
              'Providers': ['Ambulatory', 'Diagnostics and Laboratories', 'Dental Laboratories', 'Healthcare at Home',
                            'Hospitals', 'Pharmacy', 'Post Acute', 'Public Health', 'Social Services',
                            'Telehealth Services', 'Veterinary', 'Other Providers', 'Government Providers'],
              'Pharma': ['Pharma', 'Clinical Research Orgs', 'Dietary Supplements'],
              'Health Tech / Software': ['MedTech / Health Tech',
                                         'Software / Technology Supporting Providers and Hospitals',
                                         'Fitness / Health Apps'],
              'Healthcare Services': ['Health Services', 'Health Consulting'],
              'Retail': ['Apparel, Footwear, & Accessories', 'E-Retailers',
                         'Fitness & Recreation Storefronts/Facilities', 'Food, Beverage, & Convenience',
                         'Drug Stores and Pharmacies', 'Home & Hardware', 'Jewelry & Watches',
                         'Mass Merchants & Dept Stores', 'Restaurants', 'Gas Retail', 'Other Retail'],
              'Consumer Goods': ['Apparel, Footwear, & Accessory Manufacturers', 'Beverages', 'Distributors', 'Food',
                                 'Health & Beauty', 'Household Durables', 'Household Products', 'Leisure Goods',
                                 'Textiles', 'Tobacco', 'Dietary Supplements', 'MFG-Retail'],
              'Communications': ['Communications', 'Communications Equipment', 'Business Information'],
              'Media & Entertainment': ['Agency / Advertising', 'Broadcasting', 'Entertainment', 'Publishing'],
              'Agriculture': ['Agricultural Services', 'Crops', 'Livestock'],
              'Mining': ['Coal Mining & Processing', 'Metals Mining', 'Nonmetal Mining', 'Waste Services'],
              'Education Services': ['Education Related Services', 'Job Training Services'],
              'Educational Institutes': ['Colleges, Universities, and Professional Schools',
                                         'Junior Colleges and Technical Institutes', 'Primary and Secondary Schools',
                                         'Childcare / Daycare', 'Other Education'],
              'Construction': ['General Contractors', 'Home Builders', 'Sub-Contractors',
                               'Residential Solar Installation'], 'Engineering': ['Engineering'],
              'Real Estate': ['Agents, Dealers & Managers', 'Developers', 'Lessors', 'Operators'],
              'Hospitality': ['Hotels', 'Recreation'],
              'Transportation': ['Air Freight', 'Car & Truck Freight', 'Logistical Services', 'Maritime Freight',
                                 'Rail Freight', 'Storage'],
              'Travel': ['Airlines', 'Bus and Car Travel', 'Rail Travel', 'Travel Agencies & Tourism', 'Water Travel'],
              'Automotive': ['Dealers', 'OEMs'],
              'Discrete Manufacturing': ['Distribution Manufacturing', 'Parts Production', 'OEM',
                                         'Semi conductor Manufacturing', 'MFG-Retail',
                                         'Aerospace & Defense Contractors'],
              'Process Manufacturing': ['Agricultural', 'Chemicals', 'Other Process MFG'],
              'Oil & Gas': ['Oil Field Services', 'Upstream', 'Midstream', 'Downstream', 'Integrated Oil',
                            'Gas Retail'],
              'Utilities': ['Combined Electric, Gas, & Services', 'Electric & Energy Services', 'Natural Gas',
                            'Mixed Fuels', 'Public Utilities'],
              'Affiliation and Membership Groups': ['Arts, Culture, Museums, and Media', 'Associations and Unions',
                                                    'Clubs, Gyms and Community Centers, Sports and Camps',
                                                    'Membership Organizations', 'Religious Organizations'],
              'Community Development and Public Services': ['Civic Engagement, Civil, and Human Rights',
                                                            'Community Development and Services', 'Public Safety',
                                                            'Transport'],
              'Environment, Nature, and Energy': ['Animal Protection and Wildlife',
                                                  'Environment, Energy, and Agriculture'],
              'International Development, Crisis, and Relief': ['Humanitarian and Crisis Relief',
                                                                'International Development Nonprofits',
                                                                'Multilateral Organizations'],
              'Philanthropy and Foundations': ['Donations of Goods and Services', 'Philanthropy and Foundations'],
              'Research': ['Medical Research', 'Social Sciences, Policy Studies and Humanities Research'],
              'Social Services': ['Crime Prevention, Legal, Justice, and Mediation', 'Elderly Care and Services',
                                  'Employment Support and Job Training', 'Family and Youth Services',
                                  'Financial Assistance', 'Food Services, Food Banks, and Nutrition', 'Homelessness',
                                  'Housing', 'Matching, Mentorship, and Sponsorship',
                                  'Mental, Physical, and Sexual Health'],
              'Government': ['Aerospace & Defense Contractors', 'Education', 'Energy, Agriculture and Environment'],
              'Public Sector Health': ['Government Providers']}

sic_list = [{'Industry': 'Financial Services', 'Sector': 'Banking', 'Sub-Sector': 'Banks', 'Code': 6029},
            {'Industry': 'Financial Services', 'Sector': 'Banking', 'Sub-Sector': 'Credit Unions', 'Code': 6061},
            {'Industry': 'Financial Services', 'Sector': 'Banking', 'Sub-Sector': 'Lending', 'Code': 6159},
            {'Industry': 'Financial Services', 'Sector': 'Banking', 'Sub-Sector': 'Payments', 'Code': 6140},
            {'Industry': 'Financial Services', 'Sector': 'Banking', 'Sub-Sector': 'Non-Bank Holding Company',
             'Code': 6719},
            {'Industry': 'Financial Services', 'Sector': 'Capital Markets', 'Sub-Sector': 'Investment Bank',
             'Code': 6211}, {'Industry': 'Financial Services', 'Sector': 'Capital Markets',
                             'Sub-Sector': 'Security & Commodity Exchanges', 'Code': 6231},
            {'Industry': 'Financial Services', 'Sector': 'Insurance', 'Sub-Sector': 'Insurance Carriers', 'Code': 6399},
            {'Industry': 'Financial Services', 'Sector': 'Insurance', 'Sub-Sector': 'Distribution', 'Code': 6411},
            {'Industry': 'Financial Services', 'Sector': 'Insurance', 'Sub-Sector': 'Health Plans & Health Insurance',
             'Code': 6324}, {'Industry': 'Financial Services', 'Sector': 'Wealth & Asset Management',
                             'Sub-Sector': 'REITs and Other Trusts', 'Code': 6733},
            {'Industry': 'Financial Services', 'Sector': 'Wealth & Asset Management', 'Sub-Sector': 'Wealth Management',
             'Code': 6199},
            {'Industry': 'Financial Services', 'Sector': 'Wealth & Asset Management', 'Sub-Sector': 'Asset Management',
             'Code': 6722}, {'Industry': 'Financial Services', 'Sector': 'Wealth & Asset Management',
                             'Sub-Sector': 'Private Equity & Venture Capital', 'Code': 6799},
            {'Industry': 'Financial Services', 'Sector': 'Fin-Tech / Software',
             'Sub-Sector': 'Technology that performs financial services', 'Code': 6140},
            {'Industry': 'Financial Services', 'Sector': 'Fin-Tech / Software',
             'Sub-Sector': 'Software Supporting Financial Services Companies', 'Code': 7372},
            {'Industry': 'Technology', 'Sector': 'Hardware Manufacturing', 'Sub-Sector': 'Computers & Office Equipment',
             'Code': 3571},
            {'Industry': 'Technology', 'Sector': 'Hardware Manufacturing', 'Sub-Sector': 'Consumer Electronics',
             'Code': 3651},
            {'Industry': 'Technology', 'Sector': 'Hardware Manufacturing', 'Sub-Sector': 'Measurement Equipment',
             'Code': 3829},
            {'Industry': 'Technology', 'Sector': 'Hardware Manufacturing', 'Sub-Sector': 'Communications Equipment',
             'Code': 3669},
            {'Industry': 'Technology', 'Sector': 'Semiconductor & Components', 'Sub-Sector': 'Electrical Components',
             'Code': 3679}, {'Industry': 'Technology', 'Sector': 'Semiconductor & Components',
                             'Sub-Sector': 'Semi conductor Manufacturing', 'Code': 3674},
            {'Industry': 'Technology', 'Sector': 'Software & Services', 'Sub-Sector': 'Software & Programming Services',
             'Code': 7371},
            {'Industry': 'Technology', 'Sector': 'Software & Services', 'Sub-Sector': 'Technology Business Services',
             'Code': 7379}, {'Industry': 'Technology', 'Sector': 'Software & Services',
                             'Sub-Sector': 'Software supporting Financial Services', 'Code': 7372},
            {'Industry': 'Technology', 'Sector': 'Software & Services',
             'Sub-Sector': 'Technology that performs financial services', 'Code': 6140},
            {'Industry': 'Technology', 'Sector': 'Software & Services',
             'Sub-Sector': 'Software / Technology Supporting Providers and Hospitals', 'Code': 7371},
            {'Industry': 'Technology', 'Sector': 'Software & Services', 'Sub-Sector': 'Fitness / Health Apps',
             'Code': 7372},
            {'Industry': 'Technology', 'Sector': 'Software & Services', 'Sub-Sector': 'MedTech / Health Tech',
             'Code': 8099},
            {'Industry': 'Professional Services', 'Sector': 'Automobile Services', 'Sub-Sector': 'Automobile Parking',
             'Code': 7521}, {'Industry': 'Professional Services', 'Sector': 'Automobile Services',
                             'Sub-Sector': 'Miscellaneous Automotive Services', 'Code': 7549},
            {'Industry': 'Professional Services', 'Sector': 'Automobile Services',
             'Sub-Sector': 'Utility Trailer & Recreational Vehicle Rental', 'Code': 7519},
            {'Industry': 'Professional Services', 'Sector': 'Business Services',
             'Sub-Sector': 'Consumer Credit Reporting / Mercantile Services', 'Code': 7323},
            {'Industry': 'Professional Services', 'Sector': 'Business Services',
             'Sub-Sector': 'Detective, Guard, & Armored Car Services', 'Code': 7381},
            {'Industry': 'Professional Services', 'Sector': 'Business Services',
             'Sub-Sector': 'Mailing, Reproduction & Commercial Art Services', 'Code': 7334},
            {'Industry': 'Professional Services', 'Sector': 'Business Services',
             'Sub-Sector': 'Security Systems Services', 'Code': 7382},
            {'Industry': 'Professional Services', 'Sector': 'Business Services', 'Sub-Sector': 'Staffing Agencies',
             'Code': 7361}, {'Industry': 'Professional Services', 'Sector': 'Business Services',
                             'Sub-Sector': 'Miscellaneous Business Services', 'Code': 7389},
            {'Industry': 'Professional Services', 'Sector': 'Electrical Repair Shops',
             'Sub-Sector': 'Repair Shops & Related Services', 'Code': 7699},
            {'Industry': 'Professional Services', 'Sector': 'Engineering, Accounting, Research, Mgmt Services',
             'Sub-Sector': 'Accounting Services', 'Code': 8721},
            {'Industry': 'Professional Services', 'Sector': 'Engineering, Accounting, Research, Mgmt Services',
             'Sub-Sector': 'Consulting Services', 'Code': 8748},
            {'Industry': 'Professional Services', 'Sector': 'Engineering, Accounting, Research, Mgmt Services',
             'Sub-Sector': 'Management Services', 'Code': 8741},
            {'Industry': 'Professional Services', 'Sector': 'Engineering, Accounting, Research, Mgmt Services',
             'Sub-Sector': 'Public Relations', 'Code': 8743},
            {'Industry': 'Professional Services', 'Sector': 'Engineering, Accounting, Research, Mgmt Services',
             'Sub-Sector': 'Research Services', 'Code': 8732},
            {'Industry': 'Professional Services', 'Sector': 'Engineering, Accounting, Research, Mgmt Services',
             'Sub-Sector': 'Health Consulting', 'Code': 8742},
            {'Industry': 'Professional Services', 'Sector': 'Legal Services', 'Sub-Sector': 'Legal Services',
             'Code': 8111}, {'Industry': 'Professional Services', 'Sector': 'Personal Services',
                             'Sub-Sector': 'Funeral Homes & Funeral Services', 'Code': 7261},
            {'Industry': 'Professional Services', 'Sector': 'Personal Services',
             'Sub-Sector': 'Miscellaneous Personal Services', 'Code': 7200},
            {'Industry': 'Professional Services', 'Sector': 'Personal Services',
             'Sub-Sector': 'Tax Return Preparation Services', 'Code': 7291},
            {'Industry': 'Professional Services', 'Sector': 'Miscellaneous Services',
             'Sub-Sector': 'Miscellaneous Services', 'Code': 8990},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Health Plans',
             'Sub-Sector': 'Health Plans & Health Insurance', 'Code': 6324},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Medical Devices and Diagnostics',
             'Sub-Sector': 'Device Manufacturers', 'Code': 3841},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Medical Devices and Diagnostics',
             'Sub-Sector': 'Diagnostics & Laboratories', 'Code': 3821},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Providers', 'Sub-Sector': 'Ambulatory', 'Code': 8049},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Providers',
             'Sub-Sector': 'Diagnostics and Laboratories', 'Code': 8071},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Providers', 'Sub-Sector': 'Dental Laboratories',
             'Code': 8072},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Providers', 'Sub-Sector': 'Healthcare at Home',
             'Code': 8080},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Providers', 'Sub-Sector': 'Hospitals', 'Code': 8062},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Providers', 'Sub-Sector': 'Pharmacy', 'Code': 5912},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Providers', 'Sub-Sector': 'Post Acute', 'Code': 8059},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Providers', 'Sub-Sector': 'Public Health',
             'Code': 9431},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Providers', 'Sub-Sector': 'Social Services',
             'Code': 8322},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Providers', 'Sub-Sector': 'Telehealth Services',
             'Code': 8099},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Providers', 'Sub-Sector': 'Veterinary', 'Code': 742},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Providers', 'Sub-Sector': 'Other Providers',
             'Code': 8000},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Providers', 'Sub-Sector': 'Government Providers',
             'Code': 8061},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Pharma', 'Sub-Sector': 'Pharma', 'Code': 2833},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Pharma', 'Sub-Sector': 'Clinical Research Orgs',
             'Code': 8731},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Pharma', 'Sub-Sector': 'Dietary Supplements',
             'Code': 5499}, {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Health Tech / Software',
                             'Sub-Sector': 'MedTech / Health Tech', 'Code': 3841},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Health Tech / Software',
             'Sub-Sector': 'Software / Technology Supporting Providers and Hospitals', 'Code': 7371},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Health Tech / Software',
             'Sub-Sector': 'Fitness / Health Apps', 'Code': 7372},
            {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Healthcare Services', 'Sub-Sector': 'Health Services',
             'Code': 7299}, {'Industry': 'Healthcare & Life Sciences', 'Sector': 'Healthcare Services',
                             'Sub-Sector': 'Health Consulting', 'Code': 8742},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Retail',
             'Sub-Sector': 'Apparel, Footwear, & Accessories', 'Code': 5699},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Retail', 'Sub-Sector': 'E-Retailers', 'Code': 5960},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Retail',
             'Sub-Sector': 'Fitness & Recreation Storefronts/Facilities', 'Code': 7991},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Retail', 'Sub-Sector': 'Food, Beverage, & Convenience',
             'Code': 5499},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Retail', 'Sub-Sector': 'Drug Stores and Pharmacies',
             'Code': 5912},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Retail', 'Sub-Sector': 'Home & Hardware', 'Code': 5712},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Retail', 'Sub-Sector': 'Jewelry & Watches',
             'Code': 5944},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Retail', 'Sub-Sector': 'Mass Merchants & Dept Stores',
             'Code': 5311},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Retail', 'Sub-Sector': 'Restaurants', 'Code': 5812},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Retail', 'Sub-Sector': 'Gas Retail', 'Code': 5989},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Retail', 'Sub-Sector': 'Other Retail', 'Code': 5999},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Consumer Goods',
             'Sub-Sector': 'Apparel, Footwear, & Accessory Manufacturers', 'Code': 2389},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Consumer Goods', 'Sub-Sector': 'Beverages',
             'Code': 2080},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Consumer Goods', 'Sub-Sector': 'Distributors',
             'Code': 5199},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Consumer Goods', 'Sub-Sector': 'Food', 'Code': 2099},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Consumer Goods', 'Sub-Sector': 'Health & Beauty',
             'Code': 2844},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Consumer Goods', 'Sub-Sector': 'Household Durables',
             'Code': 2519},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Consumer Goods', 'Sub-Sector': 'Household Products',
             'Code': 2841},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Consumer Goods', 'Sub-Sector': 'Leisure Goods',
             'Code': 3949},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Consumer Goods', 'Sub-Sector': 'Textiles', 'Code': 2299},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Consumer Goods', 'Sub-Sector': 'Tobacco', 'Code': 2111},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Consumer Goods', 'Sub-Sector': 'Dietary Supplements',
             'Code': 5499},
            {'Industry': 'Retail & Consumer Goods', 'Sector': 'Consumer Goods', 'Sub-Sector': 'MFG-Retail',
             'Code': 5090},
            {'Industry': 'Communications & Media', 'Sector': 'Communications', 'Sub-Sector': 'Communications',
             'Code': 4899},
            {'Industry': 'Communications & Media', 'Sector': 'Communications', 'Sub-Sector': 'Communications Equipment',
             'Code': 3669},
            {'Industry': 'Communications & Media', 'Sector': 'Communications', 'Sub-Sector': 'Business Information',
             'Code': 7375}, {'Industry': 'Communications & Media', 'Sector': 'Media & Entertainment',
                             'Sub-Sector': 'Agency / Advertising', 'Code': 7311},
            {'Industry': 'Communications & Media', 'Sector': 'Media & Entertainment', 'Sub-Sector': 'Broadcasting',
             'Code': 4832},
            {'Industry': 'Communications & Media', 'Sector': 'Media & Entertainment', 'Sub-Sector': 'Entertainment',
             'Code': 7999},
            {'Industry': 'Communications & Media', 'Sector': 'Media & Entertainment', 'Sub-Sector': 'Publishing',
             'Code': 2741},
            {'Industry': 'Agriculture & Mining', 'Sector': 'Agriculture', 'Sub-Sector': 'Agricultural Services',
             'Code': 782},
            {'Industry': 'Agriculture & Mining', 'Sector': 'Agriculture', 'Sub-Sector': 'Crops', 'Code': 191},
            {'Industry': 'Agriculture & Mining', 'Sector': 'Agriculture', 'Sub-Sector': 'Livestock', 'Code': 291},
            {'Industry': 'Agriculture & Mining', 'Sector': 'Mining', 'Sub-Sector': 'Coal Mining & Processing',
             'Code': 5052},
            {'Industry': 'Agriculture & Mining', 'Sector': 'Mining', 'Sub-Sector': 'Metals Mining', 'Code': 1081},
            {'Industry': 'Agriculture & Mining', 'Sector': 'Mining', 'Sub-Sector': 'Nonmetal Mining', 'Code': 1499},
            {'Industry': 'Agriculture & Mining', 'Sector': 'Mining', 'Sub-Sector': 'Waste Services', 'Code': 4959},
            {'Industry': 'Education', 'Sector': 'Education Services', 'Sub-Sector': 'Education Related Services',
             'Code': 8299},
            {'Industry': 'Education', 'Sector': 'Education Services', 'Sub-Sector': 'Job Training Services',
             'Code': 8331}, {'Industry': 'Education', 'Sector': 'Educational Institutes',
                             'Sub-Sector': 'Colleges, Universities, and Professional Schools', 'Code': 8221},
            {'Industry': 'Education', 'Sector': 'Educational Institutes',
             'Sub-Sector': 'Junior Colleges and Technical Institutes', 'Code': 8222},
            {'Industry': 'Education', 'Sector': 'Educational Institutes', 'Sub-Sector': 'Primary and Secondary Schools',
             'Code': 8211},
            {'Industry': 'Education', 'Sector': 'Educational Institutes', 'Sub-Sector': 'Childcare / Daycare',
             'Code': 8351},
            {'Industry': 'Education', 'Sector': 'Educational Institutes', 'Sub-Sector': 'Other Education',
             'Code': 8231}, {'Industry': 'Engineering, Construction, & Real Estate', 'Sector': 'Construction',
                             'Sub-Sector': 'General Contractors', 'Code': 1522},
            {'Industry': 'Engineering, Construction, & Real Estate', 'Sector': 'Construction',
             'Sub-Sector': 'Home Builders', 'Code': 1521},
            {'Industry': 'Engineering, Construction, & Real Estate', 'Sector': 'Construction',
             'Sub-Sector': 'Sub-Contractors', 'Code': 1799},
            {'Industry': 'Engineering, Construction, & Real Estate', 'Sector': 'Construction',
             'Sub-Sector': 'Residential Solar Installation', 'Code': 1731},
            {'Industry': 'Engineering, Construction, & Real Estate', 'Sector': 'Engineering',
             'Sub-Sector': 'Engineering', 'Code': 8711},
            {'Industry': 'Engineering, Construction, & Real Estate', 'Sector': 'Real Estate',
             'Sub-Sector': 'Agents, Dealers & Managers', 'Code': 6531},
            {'Industry': 'Engineering, Construction, & Real Estate', 'Sector': 'Real Estate',
             'Sub-Sector': 'Developers', 'Code': 6552},
            {'Industry': 'Engineering, Construction, & Real Estate', 'Sector': 'Real Estate', 'Sub-Sector': 'Lessors',
             'Code': 6519},
            {'Industry': 'Engineering, Construction, & Real Estate', 'Sector': 'Real Estate', 'Sub-Sector': 'Operators',
             'Code': 6512},
            {'Industry': 'Travel, Transportation, & Hospitality', 'Sector': 'Hospitality', 'Sub-Sector': 'Hotels',
             'Code': 7011},
            {'Industry': 'Travel, Transportation, & Hospitality', 'Sector': 'Hospitality', 'Sub-Sector': 'Recreation',
             'Code': 7032}, {'Industry': 'Travel, Transportation, & Hospitality', 'Sector': 'Transportation',
                             'Sub-Sector': 'Air Freight', 'Code': 4513},
            {'Industry': 'Travel, Transportation, & Hospitality', 'Sector': 'Transportation',
             'Sub-Sector': 'Car & Truck Freight', 'Code': 4212},
            {'Industry': 'Travel, Transportation, & Hospitality', 'Sector': 'Transportation',
             'Sub-Sector': 'Logistical Services', 'Code': 4789},
            {'Industry': 'Travel, Transportation, & Hospitality', 'Sector': 'Transportation',
             'Sub-Sector': 'Maritime Freight', 'Code': 4412},
            {'Industry': 'Travel, Transportation, & Hospitality', 'Sector': 'Transportation',
             'Sub-Sector': 'Rail Freight', 'Code': 4741},
            {'Industry': 'Travel, Transportation, & Hospitality', 'Sector': 'Transportation', 'Sub-Sector': 'Storage',
             'Code': 4225},
            {'Industry': 'Travel, Transportation, & Hospitality', 'Sector': 'Travel', 'Sub-Sector': 'Airlines',
             'Code': 4581}, {'Industry': 'Travel, Transportation, & Hospitality', 'Sector': 'Travel',
                             'Sub-Sector': 'Bus and Car Travel', 'Code': 4111},
            {'Industry': 'Travel, Transportation, & Hospitality', 'Sector': 'Travel', 'Sub-Sector': 'Rail Travel',
             'Code': 4011}, {'Industry': 'Travel, Transportation, & Hospitality', 'Sector': 'Travel',
                             'Sub-Sector': 'Travel Agencies & Tourism', 'Code': 4724},
            {'Industry': 'Travel, Transportation, & Hospitality', 'Sector': 'Travel', 'Sub-Sector': 'Water Travel',
             'Code': 4489},
            {'Industry': 'Manufacturing', 'Sector': 'Automotive', 'Sub-Sector': 'Dealers', 'Code': 5511},
            {'Industry': 'Manufacturing', 'Sector': 'Automotive', 'Sub-Sector': 'OEMs', 'Code': 3711},
            {'Industry': 'Manufacturing', 'Sector': 'Discrete Manufacturing',
             'Sub-Sector': 'Distribution Manufacturing', 'Code': 5063},
            {'Industry': 'Manufacturing', 'Sector': 'Discrete Manufacturing', 'Sub-Sector': 'Parts Production',
             'Code': 3714},
            {'Industry': 'Manufacturing', 'Sector': 'Discrete Manufacturing', 'Sub-Sector': 'OEM', 'Code': 3599},
            {'Industry': 'Manufacturing', 'Sector': 'Discrete Manufacturing',
             'Sub-Sector': 'Semi conductor Manufacturing', 'Code': 3674},
            {'Industry': 'Manufacturing', 'Sector': 'Discrete Manufacturing', 'Sub-Sector': 'MFG-Retail', 'Code': 5090},
            {'Industry': 'Manufacturing', 'Sector': 'Discrete Manufacturing',
             'Sub-Sector': 'Aerospace & Defense Contractors', 'Code': 3761},
            {'Industry': 'Manufacturing', 'Sector': 'Process Manufacturing', 'Sub-Sector': 'Agricultural',
             'Code': 2879},
            {'Industry': 'Manufacturing', 'Sector': 'Process Manufacturing', 'Sub-Sector': 'Chemicals', 'Code': 5169},
            {'Industry': 'Manufacturing', 'Sector': 'Process Manufacturing', 'Sub-Sector': 'Other Process MFG',
             'Code': 5032},
            {'Industry': 'Manufacturing', 'Sector': 'Oil & Gas', 'Sub-Sector': 'Oil Field Services', 'Code': 1381},
            {'Industry': 'Manufacturing', 'Sector': 'Oil & Gas', 'Sub-Sector': 'Upstream', 'Code': 1311},
            {'Industry': 'Manufacturing', 'Sector': 'Oil & Gas', 'Sub-Sector': 'Midstream', 'Code': 4619},
            {'Industry': 'Manufacturing', 'Sector': 'Oil & Gas', 'Sub-Sector': 'Downstream', 'Code': 2911},
            {'Industry': 'Manufacturing', 'Sector': 'Oil & Gas', 'Sub-Sector': 'Integrated Oil', 'Code': 5172},
            {'Industry': 'Manufacturing', 'Sector': 'Oil & Gas', 'Sub-Sector': 'Gas Retail', 'Code': 5989},
            {'Industry': 'Manufacturing', 'Sector': 'Utilities', 'Sub-Sector': 'Combined Electric, Gas, & Services',
             'Code': 4931},
            {'Industry': 'Manufacturing', 'Sector': 'Utilities', 'Sub-Sector': 'Electric & Energy Services',
             'Code': 4911},
            {'Industry': 'Manufacturing', 'Sector': 'Utilities', 'Sub-Sector': 'Natural Gas', 'Code': 4924},
            {'Industry': 'Manufacturing', 'Sector': 'Utilities', 'Sub-Sector': 'Mixed Fuels', 'Code': 4925},
            {'Industry': 'Manufacturing', 'Sector': 'Utilities', 'Sub-Sector': 'Public Utilities', 'Code': 4941},
            {'Industry': 'Nonprofit', 'Sector': 'Affiliation and Membership Groups',
             'Sub-Sector': 'Arts, Culture, Museums, and Media', 'Code': 8511},
            {'Industry': 'Nonprofit', 'Sector': 'Affiliation and Membership Groups',
             'Sub-Sector': 'Associations and Unions', 'Code': 8512},
            {'Industry': 'Nonprofit', 'Sector': 'Affiliation and Membership Groups',
             'Sub-Sector': 'Clubs, Gyms and Community Centers, Sports and Camps', 'Code': 8513},
            {'Industry': 'Nonprofit', 'Sector': 'Affiliation and Membership Groups',
             'Sub-Sector': 'Membership Organizations', 'Code': 8699},
            {'Industry': 'Nonprofit', 'Sector': 'Affiliation and Membership Groups',
             'Sub-Sector': 'Religious Organizations', 'Code': 8661},
            {'Industry': 'Nonprofit', 'Sector': 'Community Development and Public Services',
             'Sub-Sector': 'Civic Engagement, Civil, and Human Rights', 'Code': 8521},
            {'Industry': 'Nonprofit', 'Sector': 'Community Development and Public Services',
             'Sub-Sector': 'Community Development and Services', 'Code': 8522},
            {'Industry': 'Nonprofit', 'Sector': 'Community Development and Public Services',
             'Sub-Sector': 'Public Safety', 'Code': 8523},
            {'Industry': 'Nonprofit', 'Sector': 'Community Development and Public Services', 'Sub-Sector': 'Transport',
             'Code': 8524}, {'Industry': 'Nonprofit', 'Sector': 'Environment, Nature, and Energy',
                             'Sub-Sector': 'Animal Protection and Wildlife', 'Code': 8531},
            {'Industry': 'Nonprofit', 'Sector': 'Environment, Nature, and Energy',
             'Sub-Sector': 'Environment, Energy, and Agriculture', 'Code': 8532},
            {'Industry': 'Nonprofit', 'Sector': 'International Development, Crisis, and Relief',
             'Sub-Sector': 'Humanitarian and Crisis Relief', 'Code': 8541},
            {'Industry': 'Nonprofit', 'Sector': 'International Development, Crisis, and Relief',
             'Sub-Sector': 'International Development Nonprofits', 'Code': 8542},
            {'Industry': 'Nonprofit', 'Sector': 'International Development, Crisis, and Relief',
             'Sub-Sector': 'Multilateral Organizations', 'Code': 8543},
            {'Industry': 'Nonprofit', 'Sector': 'Philanthropy and Foundations',
             'Sub-Sector': 'Donations of Goods and Services', 'Code': 8552},
            {'Industry': 'Nonprofit', 'Sector': 'Philanthropy and Foundations',
             'Sub-Sector': 'Philanthropy and Foundations', 'Code': 8551},
            {'Industry': 'Nonprofit', 'Sector': 'Research', 'Sub-Sector': 'Medical Research', 'Code': 8561},
            {'Industry': 'Nonprofit', 'Sector': 'Research',
             'Sub-Sector': 'Social Sciences, Policy Studies and Humanities Research', 'Code': 8562},
            {'Industry': 'Nonprofit', 'Sector': 'Social Services',
             'Sub-Sector': 'Crime Prevention, Legal, Justice, and Mediation', 'Code': 8571},
            {'Industry': 'Nonprofit', 'Sector': 'Social Services', 'Sub-Sector': 'Elderly Care and Services',
             'Code': 8572},
            {'Industry': 'Nonprofit', 'Sector': 'Social Services', 'Sub-Sector': 'Employment Support and Job Training',
             'Code': 8573},
            {'Industry': 'Nonprofit', 'Sector': 'Social Services', 'Sub-Sector': 'Family and Youth Services',
             'Code': 8574},
            {'Industry': 'Nonprofit', 'Sector': 'Social Services', 'Sub-Sector': 'Financial Assistance', 'Code': 8575},
            {'Industry': 'Nonprofit', 'Sector': 'Social Services',
             'Sub-Sector': 'Food Services, Food Banks, and Nutrition', 'Code': 8576},
            {'Industry': 'Nonprofit', 'Sector': 'Social Services', 'Sub-Sector': 'Homelessness', 'Code': 8577},
            {'Industry': 'Nonprofit', 'Sector': 'Social Services', 'Sub-Sector': 'Housing', 'Code': 8578},
            {'Industry': 'Nonprofit', 'Sector': 'Social Services',
             'Sub-Sector': 'Matching, Mentorship, and Sponsorship', 'Code': 8579},
            {'Industry': 'Nonprofit', 'Sector': 'Social Services', 'Sub-Sector': 'Mental, Physical, and Sexual Health',
             'Code': 8581},
            {'Industry': 'Public Sector', 'Sector': 'Government', 'Sub-Sector': 'Aerospace & Defense Contractors',
             'Code': 3760},
            {'Industry': 'Public Sector', 'Sector': 'Government', 'Sub-Sector': 'Education', 'Code': 8231},
            {'Industry': 'Public Sector', 'Sector': 'Government', 'Sub-Sector': 'Energy, Agriculture and Environment',
             'Code': 4941},
            {'Industry': 'Public Sector', 'Sector': 'Public Sector Health', 'Sub-Sector': 'Government Providers',
             'Code': 8061}]

docs = list(source_coll_4.find({}))
update_requests_final = []
update_requests_failed = []

for doc in docs:
    try:
        sic_data_str = doc.get("sic_data")
        sic_data = ast.literal_eval(sic_data_str)
    except Exception as e:
        print(e)
        continue
    try:
        if len(sic_data) != 2:
            print("sic_data length not 2 for ", doc.get("website"))
            update_requests_failed.append(UpdateOne({"website": doc.get("website")},
                                                    {"$set": {"company_name": doc.get("company_name"),
                                                              "website": doc.get("website")}}, upsert=True))
            continue
    except Exception as e:
        print(repr(e))
        update_requests_failed.append(UpdateOne({"website": doc.get("website")},
                                                {"$set": {"company_name": doc.get("company_name"),
                                                          "website": doc.get("website")}}, upsert=True))
        continue
    sub_sector = sic_data[0]
    sector = sic_data[1]
    if sector in sector_map:
        if sector not in sector_map:
            update_requests_failed.append(UpdateOne({"website": doc.get("website")},
                                                    {"$set": {"company_name": doc.get("company_name"),
                                                              "website": doc.get("website")}}, upsert=True))
            continue
        if sub_sector not in sector_map[sector]:
            update_requests_failed.append(UpdateOne({"website": doc.get("website")},
                                                    {"$set": {"company_name": doc.get("company_name"),
                                                              "website": doc.get("website")}}, upsert=True))
            continue
        flag = False
        for ele in sic_list:
            if ele["Sector"] == sector and ele["Sub-Sector"] == sub_sector:
                flag = True
                update_requests_final.append(UpdateOne({"website": doc.get("website")},
                                                       {"$set": {"company_name": doc.get("company_name"),
                                                                 "website": doc.get("website"),
                                                                 "sic_code": ele.get("Code"),
                                                                 "sector": sector,
                                                                 "sub_sector": sub_sector}}, upsert=True))
        if not flag:
            update_requests_failed.append(UpdateOne({"website": doc.get("website")},
                                                    {"$set": {"company_name": doc.get("company_name"),
                                                              "website": doc.get("website")}}, upsert=True))
target_coll.bulk_write(update_requests_final)
target_failed.bulk_write(update_requests_failed)
